### ISSUE TITLE
a license?

### ISSUE THREAD

**Issue by poetaster** [alexcrist/scaler#1]
I'm not assuming it's FOSS, but I have put it in a QT/WebView wrapper to play around on SFOS (mobile). I'm just in the habit of putting a license in my repos so I thought I'd ask before redistributing what i possibly shouldn't :)

Runs reasonably well on a Volla (aarch64 bit). I need to work out how to get local storage working (I have another WebView app where local storage works fine).

Thanks!

**Comment by alexcrist** [comment]
hey poetaster, super cool use case and very kind of you to double check on the license. 

just added the MIT license. please continue to use this project's code however you please :)

**Comment by poetaster** [comment]
thanks a bunch: https://github.com/poetaster/harbour-scaler is up. So I'll see if I can get it fluid (it works fine, but text inputs are sluggish).... and thanks again!
